name: main
on:
  push:
    branches:
      - develop
      - main
      - "feature/**"
      - "bugfix/**"
      - "hotfix/**"
      - "style/**"
  pull_request:
    branches:
      - develop
      - main
      - "feature/**"
      - "bugfix/**"
      - "hotfix/**"
      - "style/**"

env:
  NODE_VERSION: "16.x"

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: npm install, build
        run: |
          npm install
          npm i -g @railway/cli
      - name: Deploy to Railway
        run: railway up
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}